# Generated by Django 4.1 on 2022-08-26 02:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField()),
                ('time_of_commment', models.DateTimeField(default=datetime.datetime(2022, 8, 25, 22, 58, 19, 994355))),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('latest_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('initial_bid', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('time_of_creation', models.DateTimeField(default=datetime.datetime(2022, 8, 25, 22, 58, 19, 994355))),
                ('comments', models.ManyToManyField(blank=True, related_name='Comments', to='auctions.comment')),
                ('item_tags', models.ManyToManyField(blank=True, related_name='Categories', to='auctions.tag')),
                ('latest_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bid', to='auctions.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctioner_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
