# Generated by Django 4.1 on 2022-08-26 22:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_time_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='bid_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_biddings', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='latest_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 18, 55, 36, 598433)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_commment',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 18, 55, 36, 598433)),
        ),
    ]
