# Generated by Django 4.1 on 2022-08-27 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_buyer_bid_item_alter_auction_time_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 1, 10, 31, 773355)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_commment',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 1, 10, 31, 773355)),
        ),
    ]
