# Generated by Django 4.1 on 2022-08-29 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auction_time_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 51, 2, 555818)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_commment',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 51, 2, 555818)),
        ),
    ]
