# Generated by Django 4.1 on 2022-08-31 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_auction_time_of_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_commented_on', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 2, 6, 13, 615122)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_commment',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 2, 6, 13, 615122)),
        ),
    ]
