# Generated by Django 4.1 on 2022-08-31 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auction_time_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 3, 38, 1, 295976)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_commment',
            field=models.CharField(max_length=64),
        ),
    ]
