# Generated by Django 4.1 on 2022-08-31 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_auction_time_of_creation_alter_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='time_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 15, 27, 55, 450306)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default='08/31/2022, 15:27:55', max_length=200),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_wishlist', to='auctions.auction')),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
