# Generated by Django 4.1 on 2023-07-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_followinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followinglist',
            old_name='user',
            new_name='list_user',
        ),
    ]
