# Generated by Django 4.1 on 2023-08-14 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('account_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
