# Generated by Django 4.1 on 2023-08-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(),
        ),
    ]
