# Generated by Django 4.1 on 2023-08-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_entry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='account_user',
            new_name='user',
        ),
    ]
