# Generated by Django 4.1 on 2023-08-22 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_account_user_entry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publc', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('link', models.URLField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_creator', to=settings.AUTH_USER_MODEL)),
                ('savers', models.ManyToManyField(blank=True, related_name='workout_savers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
