# Generated by Django 4.1 on 2023-08-22 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='calories',
        ),
    ]
