# Generated by Django 4.1 on 2023-08-23 19:09

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_workout_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
